### ISSUE TITLE
Getting error while trying to resize the nodepool

### ISSUE THREAD

**Issue by mansilq** [estafette/estafette-gke-node-pool-shifter#12]
Below are the logs of the pod created for estafette-gke-node-pool-shifter

{"time":"2019-04-10T09:36:40Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.21","message":"Checking node pool to shift..."}
{"time":"2019-04-10T09:36:40Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.21","node-pool":"servicepool","message":"Node pool has 6 node(s), minimun wanted: 5 node(s)"}
{"time":"2019-04-10T09:36:40Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.21","node-pool":"rxnatspool","message":"Attempting to shift one node..."}
{"time":"2019-04-10T09:36:40Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.21","node-pool":"rxnatspool","message":"Adding 1 node to the pool, currently 3 node(s), expecting 4 node(s)"}
{"time":"2019-04-10T09:36:40Z","severity":"error","app":"estafette-gke-node-pool-shifter","version":"1.0.21","error":"googleapi: Error 400: Location \"\" does not exist., badRequest","node-pool":"rxnatspool","message":"Error resizing node pool"}
{"time":"2019-04-10T09:36:40Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.21","message":"Sleeping for 9s seconds..."}

Seems like, problem occurring while resizing nodepool (Unable to find correct location).
Any available solution for this ? or Are we missing something?

**Comment by umarizulkifli** [comment]
Hi,

Why the error said Error 400: 'cluster_id' or cluster in 'name' must be specified
```
kubectl get nodes
NAME                                        STATUS   ROLES    AGE    VERSION
gke-vesta-prod-durable-pool-61d165ab-w455   Ready    <none>   2d2h   v1.13.7-gke.24
gke-vesta-prod-durable-pool-7c9be55d-ptwt   Ready    <none>   2d2h   v1.13.7-gke.24
gke-vesta-prod-durable-pool-e9cfba02-xf8j   Ready    <none>   2d2h   v1.13.7-gke.24
gke-vesta-prod-pvm-pool-1e8f7fed-nqf0       Ready    <none>   10h    v1.13.7-gke.24
gke-vesta-prod-pvm-pool-f831b86a-8j1m       Ready    <none>   15h    v1.13.7-gke.24
gke-vesta-prod-pvm-pool-f88c3542-5b8z       Ready    <none>   15h    v1.13.7-gke.24
```

```
{"time":"2019-08-30T12:38:24Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","message":"Checking node pool to shift..."}
{"time":"2019-08-30T12:38:24Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"durable-pool","message":"Node pool has 3 node(s), minimun wanted: 0 node(s)"}
{"time":"2019-08-30T12:38:24Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"pvm-pool","message":"Attempting to shift one node..."}
{"time":"2019-08-30T12:38:24Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","node-pool":"pvm-pool","message":"Adding 1 node to the pool, currently 3 node(s), expecting 4 node(s)"}
{"time":"2019-08-30T12:38:24Z","severity":"error","app":"estafette-gke-node-pool-shifter","version":"1.0.11","error":"googleapi: Error 400: 'cluster_id' or cluster in 'name' must be specified., badRequest","node-pool":"pvm-pool","message":"Error resizing node pool"}
{"time":"2019-08-30T12:38:24Z","severity":"info","app":"estafette-gke-node-pool-shifter","version":"1.0.11","message":"Sleeping for 11s seconds..."}
```
