### ISSUE TITLE
Only shift some specific pods

### ISSUE THREAD

**Issue by trungdq88** [estafette/estafette-gke-node-pool-shifter#14]
This tool is shifting the kube-system internal pods (kube-dns, kube-proxy...). How do I specify a selector to only shift the pods that match?

**Comment by cre8ivejp** [comment]
@trungdq88 Hi.

I am facing something similar.
I have some pods in the non-preemptible nodes that I don't want to shift.
Did you find a way to shift the pods that match the affinity settings?

Thank you.
