### ISSUE TITLE
Production readiness status

### ISSUE THREAD

**Issue by ahume** [estafette/estafette-gke-node-pool-shifter#2]
I'm interested in the node-pool-shifter for running preemptible auto-scaling node-pools alongside our existing stable node-pools. Are you using this successfully in production clusters or is it something that is still under development or has stalled? (I notice the most recent commits are a few months ago now.)

We would potentially be interested in contributing to this if it is something that you are still actively using or developing.

(We also use the gke-preemptible-killer in some of our clusters and it's working really effectively for us. Thanks for your work on this.)

**Comment by etiennetremel** [comment]
Hi @ahume, you are more than welcome to contribute!
It has been running in production for quite some time now. You might want to run it alongside the preemptible killer to reduce the chance to have all the nodes terminating at the same time: https://github.com/estafette/estafette-gke-preemptible-killer.

**Comment by JorritSalverda** [comment]
Hi @ahume we're still actively using this controller, but it works as we require at the moment, hence no changes for a long time. I'm adding an official helm chart now, see #17 and will start to use milestones and create github releases, so it's more clear what's new and has an easier way of using it. Any contributions are more than welcome and can go into a next milestone.

**Comment by JorritSalverda** [comment]
The official Helm chart is out now and the github release documents resolved issues. Version `1.2.0` is good to go. Resolving this issue in the next milestone for completeness.
