### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by SunukKim** [estafette/estafette-gke-node-pool-shifter#7]
Missing the following package:

kubernetes.go:10:2: cannot find package "github.com/ericchiang/k8s/api/v1"

I was running the following command and couldn't get the above package.
```go build && ./estafette-gke-node-pool-shifter --node-pool-from=persistent --node-pool-to=preemptible```

**Comment by etiennetremel** [comment]
The vendor directory with all dependencies is available in this repository.
I was able to build it using the golang:1.10.2-alpine3.7 image which has a clean environment:
```
docker run -ti \
  -v $PWD:/go/src/github.com/estafette/estafette-gke-node-pool-shifter \
  -w /go/src/github.com/estafette/estafette-gke-node-pool-shifter \
  golang:1.10.2-alpine3.7 \
  go build
```

**Comment by SunukKim** [comment]
The build worked via docker; however, I received this error when trying to execute the binary file.

```./estafette-gke-node-pool-shifter: cannot execute binary file```

**Comment by etiennetremel** [comment]
Looks like you are executing a Linux binary on osx. To build for osx you should set `GOOS=darwin` in your environment before executing go build:
```
docker run -ti \
  -v $PWD:/go/src/github.com/estafette/estafette-gke-node-pool-shifter \
  -w /go/src/github.com/estafette/estafette-gke-node-pool-shifter \
  -e GOOS=darwin \
  golang:1.10.2-alpine3.7 \
  go build
```

**Comment by SunukKim** [comment]
Thank you, that did the trick.
